services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # ホストのユーザーIDとグループIDを渡す
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    volumes:
      - .:/app